/* Construction data. Coordinates and branch hints come from the project's
   60-digit verified replays (see ../scripts and ../docs). The engine recomputes
   every intersection live; 'near' only selects the branch. */
'use strict';

const GIVENS_STD = {
  points: { O: [0, 0], P: [-1, 0], B: [1, 0] },
  circle: { center: 'O', r: 1 },
  axisThru: ['P', 'B'],
};

const CONS = [

/* ================= EXISTING (historical) ================= */
{
  id: 'koch', era: 'old', name: 'Kochański’s rectification',
  author: 'Adam Kochański', year: 1685, strokes: 9, digitsExpected: 4.2266,
  constant: 'BF = √(40/3 − 2√3)·r ≈ 3.1415333·r  (a length ≈ πr, not the side)',
  badges: [{ t: 'rectification', cls: 'who' }],
  notes: 'Kochański straightens the half-circumference: BF ≈ πr to 4 decimal places. To square the circle you would still need a mean proportional between BF and r. Famous for needing only one compass opening.',
  givensCaption: 'Circle Γ with centre O; vertical diameter from A (bottom) to B (top).',
  givens: { points: { A: [0, 0], O: [0, 1], B: [0, 2] }, circle: { center: 'O', r: 1 }, axisThru: ['A', 'B'] },
  steps: [
    { objs: [{ type: 'perp', id: 'tg', thru: 'A', of: ['A', 'B'] }], pts: [],
      cap: 'Draw the tangent to Γ at A (perpendicular to the diameter at A).', cost: 3 },
    { objs: [{ type: 'circle', id: 'c1', center: 'A', thru: 'O' }],
      pts: [{ name: 'C', on: ['c1', 'GAMMA'], near: [-0.8660254, 0.5] }],
      cap: 'Circle about A through O; it cuts Γ at C.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c2', center: 'C', thru: 'A' }],
      pts: [{ name: 'D', on: ['c1', 'c2'], near: [-0.8660254, -0.5] }],
      cap: 'Circle about C through A; it cuts the first circle again at D.', cost: 1 },
    { objs: [{ type: 'line', id: 'l1', p: ['O', 'D'] }],
      pts: [{ name: 'E', on: ['l1', 'tg'], near: [-0.5773503, 0] }],
      cap: 'Line OD meets the tangent at E; AE = r/√3.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c3', center: 'E', rad: ['A', 'O'] }],
      pts: [{ name: 'E1', on: ['c3', 'tg'], near: [0.4226497, 0] }],
      cap: 'Step one radius along the tangent from E.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c4', center: 'E1', rad: ['A', 'O'] }],
      pts: [{ name: 'E2', on: ['c4', 'tg'], near: [1.4226497, 0] }],
      cap: 'A second radius step.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c5', center: 'E2', rad: ['A', 'O'] }],
      pts: [{ name: 'F', on: ['c5', 'tg'], near: [2.4226497, 0] }],
      cap: 'Third step lands at F, so EF = 3r. The segment BF ≈ πr: BF² = 4 + (3 − 1/√3)² = 40/3 − 2√3.', cost: 1 },
  ],
  answer: { p: ['B', 'F'], kind: 'length' },
},
{
  id: 'gelder', era: 'old', name: 'De Gelder’s 355/113 length',
  author: 'Jacob de Gelder', year: 1849, strokes: '≈8 compound', digitsExpected: 6.5739,
  constant: 'AH = 16/113;  π ≈ 3 + AH = 355/113  (a length, not the side)',
  badges: [{ t: 'length only', cls: 'who' }],
  notes: 'De Gelder used 355/113 = 3 + 4²/(7²+8²) but stopped at the length AH = 16/113 — he never constructed the square’s side. The side extension seen in encyclopedias is a modern editorial continuation.',
  givensCaption: 'Circle with centre M, radius r = MA; diameter through A and B.',
  givens: { points: { M: [0, 0], A: [1, 0], B: [-1, 0] }, circle: { center: 'M', r: 1 }, axisThru: ['A', 'B'] },
  steps: [
    { objs: [{ type: 'perp', id: 'mc', thru: 'M', of: ['A', 'B'] }],
      pts: [{ name: 'C', on: ['mc', 'GAMMA'], near: [0, 1] }],
      cap: 'Erect the radius MC perpendicular to AB.', cost: 3 },
    { pts: [{ name: 'E', at: [0, 0.875] }],
      cap: 'Mark E on MC with ME = ⅞·r (three successive bisections of the radius).', cost: 9 },
    { objs: [{ type: 'line', id: 'ae', p: ['A', 'E'] }],
      cap: 'Join AE. Then AE² = 1 + (7/8)² = 113/64 — this is where 7² + 8² = 113 enters.', cost: 1 },
    { pts: [{ name: 'F', at: [1 - 4 / Math.sqrt(113), 3.5 / Math.sqrt(113)] }],
      cap: 'Cut off AF = r/2 on AE (compass arc from A).', cost: 1 },
    { objs: [{ type: 'pline', id: 'fg', thru: 'F', par: ['M', 'C'] }],
      pts: [{ name: 'G', on: ['fg', 'AXIS'], near: [0.6237117, 0] }],
      cap: 'Through F draw FG parallel to MC, meeting AB at G.', cost: 3 },
    { objs: [{ type: 'line', id: 'eg', p: ['E', 'G'] }], cap: 'Join EG.', cost: 1 },
    { objs: [{ type: 'pline', id: 'fh', thru: 'F', par: ['E', 'G'] }],
      pts: [{ name: 'H', on: ['fh', 'AXIS'], near: [0.8584071, 0] }],
      cap: 'Through F draw FH parallel to EG, meeting AB at H. Similar triangles give AH = AF·AG/AE² · AE = 4²/113.', cost: 3 },
  ],
  answer: { p: ['A', 'H'], kind: 'gelder' },
},
{
  id: 'ram1913', era: 'old', name: 'Ramanujan’s squaring',
  author: 'Srinivasa Ramanujan', year: 1913, strokes: 34, digitsExpected: 6.5739,
  constant: 'RD = √(355/113)·r — the square on RD equals the circle to 6.6 digits',
  badges: [{ t: 'the classic', cls: 'who' }],
  notes: 'From “Squaring the circle”, J. Indian Math. Soc. 5, p. 132. His flourish: for a circle of 140,000 square miles, RD errs by about one inch. Stroke costs shown are an efficient primitive compilation (unverified; 24–38 depending on generosity).',
  givensCaption: 'Circle PQR with centre O and diameter PR.',
  givens: { points: { O: [0, 0], P: [-1, 0], R: [1, 0] }, circle: { center: 'O', r: 1 }, axisThru: ['P', 'R'] },
  steps: [
    { pts: [{ name: 'H', at: [-0.5, 0] }], cap: 'Bisect PO at H.', cost: 3 },
    { pts: [{ name: 'T', at: [2 / 3, 0] }], cap: 'Let T be the point of trisection of OR nearer R (OT = ⅔·r).', cost: 5 },
    { objs: [{ type: 'perp', id: 'tq', thru: 'T', of: ['P', 'R'] }],
      pts: [{ name: 'Q', on: ['tq', 'GAMMA'], near: [0.6666667, 0.7453560] }],
      cap: 'Draw TQ perpendicular to PR, meeting Γ at Q. TQ = √5/3·r.', cost: 4 },
    { objs: [{ type: 'circle', id: 'c1', center: 'R', rad: ['T', 'Q'] }],
      pts: [{ name: 'S', on: ['c1', 'GAMMA'], near: [0.7222222, -0.6916611] }],
      cap: 'Place the chord RS = TQ (the compass carries the distance to R).', cost: 1 },
    { objs: [{ type: 'line', id: 'rs', p: ['R', 'S'] }, { type: 'line', id: 'ps', p: ['P', 'S'] }],
      cap: 'Draw RS and join PS. Then PS = √31/3·r.', cost: 2 },
    { objs: [{ type: 'pline', id: 'om', thru: 'O', par: ['R', 'S'] }, { type: 'pline', id: 'tn', thru: 'T', par: ['R', 'S'] }],
      pts: [{ name: 'M', on: ['om', 'ps'], near: [-0.1388889, -0.3458305] },
            { name: 'N', on: ['tn', 'ps'], near: [0.4351852, -0.5763843] }],
      cap: 'Draw OM and TN parallel to RS, meeting PS at M and N.', cost: 6 },
    { objs: [{ type: 'circle', id: 'c2', center: 'P', rad: ['P', 'M'] }],
      pts: [{ name: 'K', on: ['c2', 'GAMMA'], near: [-0.5694444, -0.8220298] }],
      cap: 'Place a chord PK = PM.', cost: 1 },
    { objs: [{ type: 'perp', id: 'tp', thru: 'P', of: ['P', 'R'] }, { type: 'circle', id: 'c3', center: 'P', rad: ['M', 'N'] }],
      pts: [{ name: 'L', on: ['tp', 'c3'], near: [-1, -0.6185896] }],
      cap: 'Draw the tangent at P and cut off PL = MN = √31/9·r.', cost: 5 },
    { objs: [{ type: 'line', id: 'rl', p: ['R', 'L'] }, { type: 'line', id: 'rk', p: ['R', 'K'] }, { type: 'line', id: 'kl', p: ['K', 'L'] }],
      cap: 'Join RL, RK and KL. Quietly, RL = √355/9·r — the 355 has appeared.', cost: 3 },
    { objs: [{ type: 'circle', id: 'c4', center: 'R', rad: ['R', 'H'] }],
      pts: [{ name: 'C', on: ['c4', 'rk'], near: [-0.3287416, -0.6959694] }],
      cap: 'Cut off RC = RH = 3/2·r along RK.', cost: 1 },
    { objs: [{ type: 'pline', id: 'cd', thru: 'C', par: ['K', 'L'] }],
      pts: [{ name: 'D', on: ['cd', 'rl'], near: [-0.6933024, -0.5237557] }],
      cap: 'Draw CD parallel to KL, meeting RL at D. Similar triangles: RD = RL·RC/RK = √(355/113)·r.', cost: 3 },
  ],
  answer: { p: ['R', 'D'], kind: 'side' },
},
{
  id: 'ram1914', era: 'old', name: 'Ramanujan’s 8-decimal construction',
  author: 'Srinivasa Ramanujan', year: 1914, strokes: '≈27 compound', digitsExpected: 8.9970,
  constant: '3·√(OS·OB) = (9² + 19²/22)^¼ = (2143/22)^¼ ≈ π, correct to 8 decimal places',
  badges: [{ t: 'circumference/6', cls: 'who' }],
  notes: 'From “Modular equations and approximations to π” (1914): the mean proportional between OS and OB is very nearly one sixth of the circumference — error under a twelfth of an inch for an 8000-mile-diameter circle. Its magic constant works because the continued fraction of π⁴ has the giant term 16539 right after 2143/22.',
  givensCaption: 'Circle with centre O and diameter AB.',
  givens: { points: { O: [0, 0], A: [-1, 0], B: [1, 0] }, circle: { center: 'O', r: 1 }, axisThru: ['A', 'B'] },
  steps: [
    { objs: [{ type: 'perp', id: 'oc', thru: 'O', of: ['A', 'B'] }],
      pts: [{ name: 'C', on: ['oc', 'GAMMA'], near: [0, 1] }],
      cap: 'Bisect the arc ACB at C.', cost: 3 },
    { pts: [{ name: 'T', at: [-2 / 3, 0] }], cap: 'Trisect AO at T, with AT = ⅓·r.', cost: 5 },
    { objs: [{ type: 'line', id: 'bc', p: ['B', 'C'] }], cap: 'Join BC.', cost: 1 },
    { objs: [{ type: 'circle', id: 'cm', center: 'C', rad: ['A', 'T'] }],
      pts: [{ name: 'M', on: ['cm', 'bc'], near: [0.2357023, 0.7642977] }],
      cap: 'Cut off CM = AT along BC.', cost: 1 },
    { objs: [{ type: 'circle', id: 'cn', center: 'M', rad: ['A', 'T'] }],
      pts: [{ name: 'N', on: ['cn', 'bc'], near: [0.4714045, 0.5285955] }],
      cap: 'Cut off MN = AT.', cost: 1 },
    { objs: [{ type: 'line', id: 'am', p: ['A', 'M'] }, { type: 'line', id: 'an', p: ['A', 'N'] }],
      cap: 'Join AM and AN.', cost: 2 },
    { objs: [{ type: 'circle', id: 'cp', center: 'A', rad: ['A', 'M'] }],
      pts: [{ name: 'P', on: ['cp', 'an'], near: [0.3673898, 0.4912290] }],
      cap: 'Cut off AP = AM on AN.', cost: 1 },
    { objs: [{ type: 'pline', id: 'pq', thru: 'P', par: ['M', 'N'] }],
      pts: [{ name: 'Q', on: ['pq', 'am'], near: [0.1483426, 0.7102653] }],
      cap: 'Through P draw PQ parallel to MN, meeting AM at Q.', cost: 3 },
    { objs: [{ type: 'line', id: 'oq', p: ['O', 'Q'] }], cap: 'Join OQ.', cost: 1 },
    { objs: [{ type: 'pline', id: 'tr', thru: 'T', par: ['O', 'Q'] }],
      pts: [{ name: 'R', on: ['tr', 'am'], near: [-0.6172231, 0.2367697] }],
      cap: 'Through T draw TR parallel to OQ, meeting AQ at R.', cost: 3 },
    { objs: [{ type: 'perp', id: 'sa', thru: 'A', of: ['A', 'B'] }, { type: 'circle', id: 'cs', center: 'A', rad: ['A', 'R'] }],
      pts: [{ name: 'S', on: ['sa', 'cs'], near: [-1, 0.4500947] }],
      cap: 'Draw AS perpendicular to AB with AS = AR.', cost: 5 },
    { objs: [{ type: 'line', id: 'os', p: ['O', 'S'] }],
      cap: 'Join OS. The mean proportional between OS and OB is very nearly a sixth of the circumference: π ≈ 3·√(OS·OB).', cost: 1 },
  ],
  answer: { p: ['O', 'S'], kind: 'r1914' },
},

/* ================= NEW (this project) ================= */
{
  id: 'f5-4', era: 'new', name: '4-stroke (search)',
  author: 'Fable 5 search', year: 2026, strokes: 4, digitsExpected: 4.4154,
  constant: 's = S₁S₂;  s² ≈ π to 4.42 digits — already beats the published 13-stroke record',
  badges: [{ t: 'tangency', cls: 'warn' }, { t: '2 transfers', cls: 'who' }],
  notes: 'E is a point of internal tangency of c₁ and c₂ — legal as a constructed point, but under a strict transversal-only rule you must draw line VB first (+1 stroke), after which this is dominated by the 5-stroke.',
  givens: GIVENS_STD,
  steps: [
    { objs: [{ type: 'circle', id: 'c1', center: 'B', thru: 'O' }],
      pts: [{ name: 'D', on: ['c1', 'AXIS'], near: [2, 0] },
            { name: 'V', on: ['c1', 'GAMMA'], near: [0.5, 0.8660254] },
            { name: "V'", on: ['c1', 'GAMMA'], near: [0.5, -0.8660254] }],
      cap: 'Circle about B through O. Free intersections: D = (2,0) on the axis, V and V′ on Γ.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c2', center: 'V', rad: ['D', 'O'] }],
      pts: [{ name: 'A', on: ['c2', 'AXIS'], near: [-1.3027756, 0] },
            { name: 'E', on: ['c1', 'c2'], near: [1.5, -0.8660254] }],
      cap: 'Circle about V with radius DO = 2r (transfer). It cuts the axis at A — and touches c₁ at the single tangency point E.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c3', center: "V'", rad: ['B', 'A'] }],
      cap: 'Circle about V′ with radius BA = (1+√13)/2·r (transfer).', cost: 1 },
    { objs: [{ type: 'line', id: 'l4', p: ['A', 'E'] }],
      pts: [{ name: 'S1', on: ['l4', 'c1'], near: [0.0986122, -0.4330127] },
            { name: 'S2', on: ['l4', 'c3'], near: [-1.5948335, 0.0902425] }],
      cap: 'Line AE cuts c₁ at S₁ and c₃ at S₂. The segment S₁S₂ is the side.', cost: 1 },
  ],
  answer: { p: ['S1', 'S2'], kind: 'side' },
},
{
  id: 'f5-5', era: 'new', name: '5-stroke, closed form (search)',
  author: 'Fable 5 search', year: 2026, strokes: 5, digitsExpected: 6.2418,
  constant: 's = [2 + (√42 − √15 − √(21−3√15))/2]·r',
  badges: [{ t: '3 transfers', cls: 'who' }],
  notes: 'Both endpoints land on the given diameter, so the answer segment costs nothing. Five strokes for six digits — one stroke per 1.25 digits.',
  givens: GIVENS_STD,
  steps: [
    { objs: [{ type: 'circle', id: 'c1', center: 'P', thru: 'O' }],
      pts: [{ name: 'A1', on: ['c1', 'AXIS'], near: [-2, 0] }],
      cap: 'Circle about P through O; A₁ = (−2, 0) on the axis.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c2', center: 'B', thru: 'P' }],
      pts: [{ name: 'V1', on: ['c1', 'c2'], near: [-0.75, 0.9682458] },
            { name: 'V2', on: ['c1', 'c2'], near: [-0.75, -0.9682458] },
            { name: 'M', on: ['c2', 'AXIS'], near: [3, 0] }],
      cap: 'Circle about B through P (radius 2r): V₁, V₂ on c₁ and M = (3, 0).', cost: 1 },
    { objs: [{ type: 'circle', id: 'c3', center: 'O', rad: ['V1', 'V2'] }],
      pts: [{ name: 'T', on: ['c3', 'AXIS'], near: [-1.9364917, 0] },
            { name: 'N', on: ['c2', 'c3'], near: [0.375, -1.8998355] }],
      cap: 'Circle about O with radius V₁V₂ = √15/2 (transfer): T on the axis, N on c₂.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c4', center: 'A1', rad: ['V1', 'T'] }],
      pts: [{ name: 'I1', on: ['c4', 'AXIS'], near: [-0.4685750, 0] }],
      cap: 'Circle about A₁ with radius V₁T = √(21−3√15)/2 (transfer) marks I₁.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c5', center: 'T', rad: ['M', 'N'] }],
      pts: [{ name: 'I2', on: ['c5', 'AXIS'], near: [1.3038787, 0] }],
      cap: 'Circle about T with radius MN = √42/2 (transfer) marks I₂. I₁I₂ on the given diameter is the side.', cost: 1 },
  ],
  answer: { p: ['I1', 'I2'], kind: 'side' },
},
{
  id: 'f5-6', era: 'new', name: '6-stroke, transfer-free (search)',
  author: 'Fable 5 search', year: 2026, strokes: 6, digitsExpected: 7.3682,
  constant: 's = |RS| (the radius of the final circle), marked as RT on the axis',
  badges: [{ t: 'collapsing-pure', cls: 'pure' }, { t: '7 under Beatrix rules', cls: 'pure' }],
  notes: 'Every circle is centred on one constructed point through another — no rigid-compass transfers, so the count stands under strict Euclid rules. Under Beatrix’s own two-point convention this costs 7 strokes vs his 13, at 7.37 digits vs 4.32.',
  givens: GIVENS_STD,
  steps: [
    { objs: [{ type: 'circle', id: 'c1', center: 'P', thru: 'B' }],
      pts: [{ name: 'P3', on: ['c1', 'AXIS'], near: [-3, 0] }],
      cap: 'Circle about P through B (radius 2r); P₃ = (−3, 0).', cost: 1 },
    { objs: [{ type: 'circle', id: 'c2', center: 'P3', thru: 'O' }],
      pts: [{ name: 'M', on: ['GAMMA', 'c2'], near: [-0.1666667, -0.9860133] },
            { name: 'N', on: ['c1', 'c2'], near: [-0.75, -1.9843135] },
            { name: "N'", on: ['c1', 'c2'], near: [-0.75, 1.9843135] }],
      cap: 'Circle about P₃ through O (radius 3r): M on Γ, N and N′ on c₁.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c3', center: 'M', thru: 'N' }],
      pts: [{ name: 'R', on: ['c3', 'AXIS'], near: [-0.7705365, 0] }],
      cap: 'Circle about M through N (r² = 7(3−√5)/4). Its left axis intersection is R.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c4', center: "N'", thru: 'B' }],
      pts: [{ name: 'Q', on: ['c3', 'c4'], near: [0.7044877, -0.2257692] }],
      cap: 'Circle about N′ through B (radius √7·r); it meets c₃ at Q, the intersection inside Γ.', cost: 1 },
    { objs: [{ type: 'line', id: 'l5', p: ['P3', 'Q'] }],
      pts: [{ name: 'S', on: ['l5', 'c1'], near: [0.9851979, -0.2428770] }],
      cap: 'Line P₃Q meets c₁ again at S (the intersection other than P₃’s side).', cost: 1 },
    { objs: [{ type: 'circle', id: 'c6', center: 'R', thru: 'S' }],
      pts: [{ name: 'T', on: ['c6', 'AXIS'], near: [-2.5429904, 0] }],
      cap: 'Circle about R through S: its radius |RS| is the side. It marks T on the axis, so RT is the answer segment.', cost: 1 },
  ],
  answer: { p: ['R', 'T'], kind: 'side' },
},
{
  id: 'f5-7', era: 'new', name: '7-stroke, transfer-free (search)',
  author: 'Fable 5 search', year: 2026, strokes: 7, digitsExpected: 8.0484,
  constant: 's = A′K — eight digits of π from seven collapsing-compass strokes',
  badges: [{ t: 'collapsing-pure', cls: 'pure' }, { t: '8 under Beatrix rules', cls: 'pure' }],
  notes: 'More digits than Ramanujan’s 1914 construction (~58 strokes) from seven strokes. Zero transfers: the count stands under the strictest classical rules.',
  givens: GIVENS_STD,
  steps: [
    { objs: [{ type: 'circle', id: 'c1', center: 'P', thru: 'O' }],
      pts: [{ name: 'A', on: ['c1', 'AXIS'], near: [-2, 0] },
            { name: 'E', on: ['GAMMA', 'c1'], near: [-0.5, 0.8660254] }],
      cap: 'Circle about P through O: A = (−2, 0), E on Γ.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c2', center: 'A', thru: 'P' }],
      pts: [{ name: "A'", on: ['c2', 'AXIS'], near: [-3, 0] },
            { name: 'D', on: ['c1', 'c2'], near: [-1.5, -0.8660254] }],
      cap: 'Circle about A through P: A′ = (−3, 0) and the lower vesica point D.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c3', center: 'D', thru: 'O' }],
      pts: [{ name: 'F', on: ['GAMMA', 'c3'], near: [-0.7287136, 0.6848186] },
            { name: 'G', on: ['GAMMA', 'c3'], near: [0.2287136, -0.9734938] }],
      cap: 'Circle about D through O (radius √3·r) cuts Γ at F (upper) and G (lower); F_x, G_x = (−3∓√33)/12.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c4', center: 'F', thru: 'O' }],
      pts: [{ name: 'H', on: ['c4', 'AXIS'], near: [-1.4574271, 0] }],
      cap: 'Circle about F through O marks H on the axis.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c5', center: 'E', thru: 'G' }],
      pts: [{ name: 'J', on: ['c5', 'AXIS'], near: [-2.2790037, 0] }],
      cap: 'Circle about E through G marks J on the axis.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c6', center: 'H', thru: 'J' }],
      pts: [{ name: 'K', on: ['c2', 'c6'], near: [-1.4292037, 0.8210917] }],
      cap: 'Circle about H through J meets c₂ at K (upper).', cost: 1 },
    { objs: [{ type: 'line', id: 'l7', p: ["A'", 'K'] }],
      cap: 'The line A′K is the answer segment itself.', cost: 1 },
  ],
  answer: { p: ["A'", 'K'], kind: 'side' },
},
{
  id: 'f5-8', era: 'new', name: '8-stroke (search)',
  author: 'Fable 5 search', year: 2026, strokes: 8, digitsExpected: 8.1721,
  constant: 's = PX on the given diameter — one endpoint is the given point P',
  badges: [{ t: '3 transfers', cls: 'who' }],
  notes: 'A radius-4r arc swung from below the circle places X with eight-digit precision. Sol 5.6’s review showed c₅ is collapsing-legal (|W′P| = 2 exactly), cutting the transfer count from 4 to 3.',
  givens: GIVENS_STD,
  steps: [
    { objs: [{ type: 'circle', id: 'c1', center: 'P', thru: 'B' }],
      pts: [{ name: 'E0', on: ['c1', 'AXIS'], near: [-3, 0] }],
      cap: 'Circle about P through B; E₀ = (−3, 0).', cost: 1 },
    { objs: [{ type: 'circle', id: 'c2', center: 'B', thru: 'P' }],
      pts: [{ name: 'W', on: ['c1', 'c2'], near: [0, 1.7320508] },
            { name: "W'", on: ['c1', 'c2'], near: [0, -1.7320508] },
            { name: 'R', on: ['c2', 'AXIS'], near: [3, 0] }],
      cap: 'Circle about B through P: vesica points W, W′ and R = (3, 0).', cost: 1 },
    { objs: [{ type: 'line', id: 'l3', p: ['W', "W'"] }],
      pts: [{ name: 'N', on: ['l3', 'GAMMA'], near: [0, -1] }],
      cap: 'Line WW′ (the perpendicular diameter); N = (0, −1) on Γ.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c4', center: 'W', rad: ['O', 'R'] }],
      cap: 'Circle about W with radius OR = 3r (transfer).', cost: 1 },
    { objs: [{ type: 'circle', id: 'c5', center: "W'", thru: 'P' }],
      pts: [{ name: 'E', on: ['c5', 'c2'], near: [2, -1.7320508] },
            { name: 'A', on: ['c5', 'c4'], near: [-1.7260262, -0.7216878] }],
      cap: 'Circle about W′ through P (|W′P| = 2r exactly — collapsing-legal, per the review): E on c₂, A on c₄.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c6', center: 'O', rad: ['N', 'A'] }],
      pts: [{ name: 'D', on: ['c6', 'c4'], near: [-1.5279623, -0.8496790] }],
      cap: 'Circle about O with radius NA (transfer; r² = (27−5√3)/6): D on c₄.', cost: 1 },
    { objs: [{ type: 'line', id: 'l7', p: ['E', 'D'] }],
      pts: [{ name: 'M', on: ['l7', 'c6'], near: [0.9480546, -1.4689509] }],
      cap: 'Line ED. D already lies on c₆, so the line meets c₆ again at M.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c8', center: 'M', rad: ['R', 'P'] }],
      pts: [{ name: 'X', on: ['c8', 'AXIS'], near: [-2.7724538, 0] }],
      cap: 'Circle about M with radius RP = 4r (transfer) lands X on the axis. PX is the side — with the given point P as one endpoint.', cost: 1 },
  ],
  answer: { p: ['P', 'X'], kind: 'side' },
},
{
  id: 'f5-9', era: 'new', name: '9-stroke (search)',
  author: 'Fable 5 search', year: 2026, strokes: 9, digitsExpected: 8.9850,
  constant: 's = E₁E₂ — nine digits of π, matching Chu 2019 (≥68 strokes) at 9 strokes',
  badges: [{ t: '2 transfers', cls: 'who' }],
  notes: 'The review showed c₂ and c₇ are collapsing-legal (|PV₊| = √3 and |GB| = 1 exactly), cutting the transfer count from 4 to 2, and confirmed the c₄→c₅ erratum via |LB|² = 4.',
  givens: GIVENS_STD,
  steps: [
    { objs: [{ type: 'circle', id: 'c1', center: 'B', thru: 'O' }],
      pts: [{ name: 'D', on: ['c1', 'AXIS'], near: [2, 0] },
            { name: 'V+', on: ['c1', 'GAMMA'], near: [0.5, 0.8660254] },
            { name: 'V-', on: ['c1', 'GAMMA'], near: [0.5, -0.8660254] }],
      cap: 'Circle about B through O: D = (2, 0), V₊ and V₋ on Γ.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c2', center: 'P', thru: 'V+' }],
      pts: [{ name: 'F', on: ['c2', 'AXIS'], near: [0.7320508, 0] }],
      cap: 'Circle about P through V₊ (|PV₊| = √3·r exactly — collapsing-legal): F = (√3−1, 0).', cost: 1 },
    { objs: [{ type: 'circle', id: 'c3', center: 'B', rad: ['F', 'V-'] }],
      pts: [{ name: 'E1', on: ['c3', 'c2'], near: [0.5490381, 0.7749071] }],
      cap: 'Circle about B with radius FV₋ (transfer; r² = 6−3√3): E₁ on c₂ — the first endpoint of the answer.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c4', center: 'P', thru: 'B' }],
      pts: [{ name: 'G', on: ['c1', 'c4'], near: [0.75, 0.9682458] }],
      cap: 'Circle about P through B: G = (¾, √15/4) on c₁.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c5', center: 'B', thru: 'P' }],
      pts: [{ name: 'R', on: ['c5', 'AXIS'], near: [3, 0] }],
      cap: 'Circle about B through P: R = (3, 0).', cost: 1 },
    { objs: [{ type: 'line', id: 'l6', p: ['D', 'V+'] }],
      pts: [{ name: 'L', on: ['l6', 'c5'], near: [-0.4270510, 1.4012585] }],
      cap: 'Line DV₊ (incidentally tangent to Γ at V₊) meets c₅ up-left at L, L_x = (5−3√5)/4. (The search write-up said c₄; the audit proved |LB|² = 4, so c₅.)', cost: 1 },
    { objs: [{ type: 'circle', id: 'c7', center: 'G', thru: 'B' }],
      pts: [{ name: 'H', on: ['c7', 'GAMMA'], near: [-0.25, 0.9682458] },
            { name: 'K', on: ['l6', 'c7'], near: [1.4892899, 0.2948586] }],
      cap: 'Circle about G through B (|GB| = 1 exactly): H = the c₇∩Γ point other than B, and K on line l₆.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c8', center: 'H', rad: ['K', 'L'] }],
      pts: [{ name: 'E2', on: ['c8', 'c1'], near: [0.7996950, -0.9797336] }],
      cap: 'Circle about H with radius KL (transfer): E₂ on c₁, the second endpoint.', cost: 1 },
    { objs: [{ type: 'line', id: 'l9', p: ['E1', 'E2'] }],
      cap: 'The line E₁E₂ is the answer segment.', cost: 1 },
  ],
  answer: { p: ['E1', 'E2'], kind: 'side' },
},
{
  id: 'sol14', era: 'new', name: '14-stroke 355/113',
  author: 'Sol 5.6 (ChatGPT)', year: 2026, strokes: 14, digitsExpected: 6.5739,
  constant: 'IW² = OW² + OI² = 3 + 16/113 = 355/113 — Ramanujan’s constant, zero transfers',
  badges: [{ t: 'collapsing-pure', cls: 'pure' }, { t: '355/113', cls: 'who' }],
  notes: 'Every circle is centred on a constructed point through another, so 14 stands even under strict collapsing-compass rules. The 7:8 direction is manufactured by the radical line of two circles through O; the mirror-chord trick drops the perpendicular in one stroke.',
  givens: GIVENS_STD,
  steps: [
    { objs: [{ type: 'circle', id: 'c1', center: 'P', thru: 'B' }, { type: 'circle', id: 'c2', center: 'B', thru: 'P' }],
      pts: [{ name: 'W', on: ['c1', 'c2'], near: [0, 1.7320508] }],
      cap: 'Two radius-2r circles about P and B; their upper intersection is W = (0, √3).', cost: 2 },
    { objs: [{ type: 'line', id: 'l1', p: ['O', 'W'] }],
      pts: [{ name: 'Q', on: ['l1', 'GAMMA'], near: [0, 1] }],
      cap: 'Line OW (the perpendicular diameter) meets Γ at Q = (0, r).', cost: 1 },
    { objs: [{ type: 'circle', id: 'c3', center: 'B', thru: 'O' }, { type: 'circle', id: 'c4', center: 'Q', thru: 'O' }],
      pts: [{ name: 'X1', on: ['GAMMA', 'c3'], near: [0.5, 0.8660254] },
            { name: 'X2', on: ['GAMMA', 'c3'], near: [0.5, -0.8660254] }],
      cap: 'Two unit circles, about B and about Q, both through O.', cost: 2 },
    { objs: [{ type: 'line', id: 'l2', p: ['X1', 'X2'] }],
      pts: [{ name: 'X', on: ['l2', 'AXIS'], near: [0.5, 0] }],
      cap: 'Common chord of Γ and c₃ meets the diameter at X = r/2.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c5', center: 'O', thru: 'X' }],
      cap: 'Half-radius circle about O through X.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c6', center: 'B', thru: 'X' }],
      pts: [{ name: 'G1', on: ['GAMMA', 'c6'], near: [0.875, 0.4841229] },
            { name: 'G2', on: ['GAMMA', 'c6'], near: [0.875, -0.4841229] }],
      cap: 'Circle about B through X.', cost: 1 },
    { objs: [{ type: 'line', id: 'l3', p: ['G1', 'G2'] }],
      pts: [{ name: 'G', on: ['l3', 'AXIS'], near: [0.875, 0] }],
      cap: 'Its common chord with Γ meets the axis at G = 7r/8 (powers of the point: g²−r² = (r−g)²−(r/2)²).', cost: 1 },
    { objs: [{ type: 'circle', id: 'c7', center: 'G', thru: 'O' }],
      pts: [{ name: 'K', on: ['c7', 'c4'], near: [0.9911504, 0.8672566] }],
      cap: 'Circle about G through O. It meets c₄ (also through O) again at K; the radical line OK ⊥ QG has direction (8, 7).', cost: 1 },
    { objs: [{ type: 'line', id: 'l4', p: ['O', 'K'] }],
      pts: [{ name: 'H', on: ['l4', 'c5'], near: [0.3762883, 0.3292523] }],
      cap: 'Line OK cuts the half-radius circle at H, |OH| = r/2.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c8', center: 'X', thru: 'H' }],
      pts: [{ name: "H'", on: ['c8', 'c5'], near: [0.3762883, -0.3292523] }],
      cap: 'Circle about X through H meets c₅ again at the mirror point H′.', cost: 1 },
    { objs: [{ type: 'line', id: 'l5', p: ['H', "H'"] }],
      pts: [{ name: 'I', on: ['l5', 'AXIS'], near: [0.3762883, 0] }],
      cap: 'The chord HH′ is vertical (both centres lie on the axis): it drops the perpendicular for free. I = 4r/√113.', cost: 1 },
    { objs: [{ type: 'line', id: 'l6', p: ['I', 'W'] }],
      cap: 'IW is the side: IW² = OW² + OI² = 3 + 16/113 = 355/113.', cost: 1 },
  ],
  answer: { p: ['I', 'W'], kind: 'side' },
},
{
  id: 'f5-15', era: 'new', name: '15-move 355/113',
  author: 'Fable 5', year: 2026, strokes: 15, digitsExpected: 6.5739,
  constant: 'GK² = 3 + 16/113 = 355/113 — legs √3·r and 4r/√113',
  badges: [{ t: '355/113', cls: 'who' }, { t: '4 transfers', cls: 'who' }],
  notes: 'The circle is squared by one right triangle: legs √3·r (vesica) and 4r/√113 (a leg-projection in the half-scale 7-8-√113 triangle). Radical-axis shortcuts put the verticals at 7/8 and 7/16 in two strokes each.',
  givens: GIVENS_STD,
  steps: [
    { objs: [{ type: 'circle', id: 'c1', center: 'B', thru: 'O' }],
      pts: [{ name: 'F', on: ['c1', 'GAMMA'], near: [0.5, 0.8660254] },
            { name: "F'", on: ['c1', 'GAMMA'], near: [0.5, -0.8660254] }],
      cap: 'Circle about B through O cuts Γ at F, F′.', cost: 1 },
    { objs: [{ type: 'line', id: 'l1', p: ['F', "F'"] }],
      pts: [{ name: 'X', on: ['l1', 'AXIS'], near: [0.5, 0] }],
      cap: 'Line FF′: |FF′| = √3·r, and X = midpoint of OB.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c2', center: 'B', thru: 'X' }],
      pts: [{ name: 'V', on: ['GAMMA', 'c2'], near: [0.875, 0.4841229] },
            { name: "V'", on: ['GAMMA', 'c2'], near: [0.875, -0.4841229] }],
      cap: 'Circle about B through X (radius r/2) cuts Γ on the vertical x = 7/8 (radical-axis identity x = 1 − ρ²/2).', cost: 1 },
    { objs: [{ type: 'line', id: 'l2', p: ['V', "V'"] }],
      pts: [{ name: 'Z', on: ['l2', 'AXIS'], near: [0.875, 0] }],
      cap: 'Line VV′ meets the axis at Z = 7r/8.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c3', center: 'Z', rad: ['O', 'B'] }],
      pts: [{ name: 'W', on: ['GAMMA', 'c3'], near: [0.4375, 0.8992184] },
            { name: "W'", on: ['GAMMA', 'c3'], near: [0.4375, -0.8992184] }],
      cap: 'Unit-radius circle about Z (transfer): it cuts Γ on the vertical x = 7/16.', cost: 1 },
    { objs: [{ type: 'line', id: 'l3', p: ['W', "W'"] }],
      pts: [{ name: "Z'", on: ['l3', 'AXIS'], near: [0.4375, 0] }],
      cap: 'Line WW′ meets the axis at Z′ = 7r/16.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c4', center: "Z'", rad: ['X', 'B'] }],
      pts: [{ name: 'U', on: ['c4', 'l3'], near: [0.4375, 0.5] }],
      cap: 'Circle about Z′ with radius XB = r/2 (transfer): U = (7/16, 1/2).', cost: 1 },
    { objs: [{ type: 'line', id: 'l4', p: ['O', 'U'] }],
      cap: 'Line OU: the hypotenuse, |OU| = √113/16 (legs 7/16 and 1/2).', cost: 1 },
    { objs: [{ type: 'circle', id: 'c5', center: "Z'", thru: 'O' }],
      pts: [{ name: "O''", on: ['c5', 'l4'], near: [0.3794248, 0.4336283] }],
      cap: 'Circle about Z′ through O cuts OU again at O″.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c6', center: 'O', thru: "O''" }],
      cap: 'First bisection circle (about O through O″).', cost: 1 },
    { objs: [{ type: 'circle', id: 'c7', center: "O''", thru: 'O' }],
      pts: [{ name: 'Y1', on: ['c6', 'c7'], near: [-0.1859, 0.5455] },
            { name: 'Y2', on: ['c6', 'c7'], near: [0.5653, -0.1119] }],
      cap: 'Second bisection circle (about O″ through O).', cost: 1 },
    { objs: [{ type: 'line', id: 'l5', p: ['Y1', 'Y2'] }],
      pts: [{ name: 'Hf', on: ['l5', 'l4'], near: [0.1897124, 0.2168142] }],
      cap: 'Perpendicular bisector of OO″ meets OU at H — the foot of the perpendicular from Z′. UH = (r/2)²/|OU| = 4r/√113.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c8', center: "Z'", rad: ['F', "F'"] }],
      pts: [{ name: 'G', on: ['c8', 'l3'], near: [0.4375, 1.7320508] }],
      cap: 'Circle about Z′ with radius FF′ = √3·r (transfer): G on the vertical.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c9', center: "Z'", rad: ['U', 'Hf'] }],
      pts: [{ name: 'K', on: ['c9', 'AXIS'], near: [0.8137883, 0] }],
      cap: 'Circle about Z′ with radius UH = 4r/√113 (transfer): K on the axis.', cost: 1 },
    { objs: [{ type: 'line', id: 'l6', p: ['G', 'K'] }],
      cap: 'GK is the side: GK² = Z′G² + Z′K² = 3 + 16/113 = 355/113.', cost: 1 },
  ],
  answer: { p: ['G', 'K'], kind: 'side' },
},
{
  id: 'sol28', era: 'new', name: '28-stroke high accuracy',
  author: 'Sol 5.6 (ChatGPT)', year: 2026, strokes: 28, digitsExpected: 10.4209,
  constant: 'JL² = 355/113 − 1/44⁴ — 10.4 digits of π',
  badges: [{ t: '10.4 digits', cls: 'pure' }, { t: 'undraftable', cls: 'warn' }],
  notes: 'Builds the 14-stroke figure through I, then removes 1/44⁴ by Pythagoras: BU = r/44 and BV = r/1936 via two intercept steps, then JL² = WI² − BV². Exact in theory; r/1936 is ~0.5 mm on a metre drawing. Audited at exactly 28 strokes (a 27 exists via a tangency shortcut).',
  givens: GIVENS_STD,
  clip: [-5.2, -2.7, 7.0, 3.3],
  hideLabels: false,
  steps: [
    { objs: [{ type: 'circle', id: 'c1', center: 'P', thru: 'B' }, { type: 'circle', id: 'c2', center: 'B', thru: 'P' }],
      pts: [{ name: 'W', on: ['c1', 'c2'], near: [0, 1.7320508] },
            { name: 'E3', on: ['c1', 'AXIS'], near: [-3, 0] }],
      cap: 'Base figure, strokes 1–2: radius-2r circles about P and B; W = (0, √3). (E = (−3,0) also arrives free.)', cost: 2 },
    { objs: [{ type: 'line', id: 'l1', p: ['O', 'W'] }],
      pts: [{ name: 'Q', on: ['l1', 'GAMMA'], near: [0, 1] }],
      cap: 'Line OW; Q = (0, r).', cost: 1 },
    { objs: [{ type: 'circle', id: 'c3', center: 'B', thru: 'O' }, { type: 'circle', id: 'c4', center: 'Q', thru: 'O' }],
      pts: [{ name: 'X1', on: ['GAMMA', 'c3'], near: [0.5, 0.8660254] },
            { name: 'X2', on: ['GAMMA', 'c3'], near: [0.5, -0.8660254] },
            { name: 'C', on: ['c3', 'c4'], near: [1, 1] }],
      cap: 'Unit circles about B and Q. Their second intersection C = (1, 1) will matter later.', cost: 2 },
    { objs: [{ type: 'line', id: 'l2', p: ['X1', 'X2'] }],
      pts: [{ name: 'X', on: ['l2', 'AXIS'], near: [0.5, 0] }],
      cap: 'Chord of Γ and c₃ gives X = r/2.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c5', center: 'O', thru: 'X' }], cap: 'Half-radius circle.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c6', center: 'B', thru: 'X' }],
      pts: [{ name: 'G1', on: ['GAMMA', 'c6'], near: [0.875, 0.4841229] },
            { name: 'G2', on: ['GAMMA', 'c6'], near: [0.875, -0.4841229] }],
      cap: 'Circle about B through X.', cost: 1 },
    { objs: [{ type: 'line', id: 'l3', p: ['G1', 'G2'] }],
      pts: [{ name: 'G', on: ['l3', 'AXIS'], near: [0.875, 0] }],
      cap: 'G = 7r/8 on the axis.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c7', center: 'G', thru: 'O' }],
      pts: [{ name: 'K', on: ['c7', 'c4'], near: [0.9911504, 0.8672566] }],
      cap: 'Circle about G through O; K on c₄ gives the 7:8 radical direction.', cost: 1 },
    { objs: [{ type: 'line', id: 'l4', p: ['O', 'K'] }],
      pts: [{ name: 'H', on: ['l4', 'c5'], near: [0.3762883, 0.3292523] }],
      cap: 'Line OK; H at |OH| = r/2.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c8', center: 'X', thru: 'H' }],
      pts: [{ name: "H'", on: ['c8', 'c5'], near: [0.3762883, -0.3292523] }],
      cap: 'Mirror circle about X through H.', cost: 1 },
    { objs: [{ type: 'line', id: 'l5', p: ['H', "H'"] }],
      pts: [{ name: 'I', on: ['l5', 'AXIS'], near: [0.3762883, 0] }],
      cap: 'Vertical chord HH′ drops I = 4r/√113. Base complete at 13 strokes: WI² = 355/113 (IW left undrawn).', cost: 1 },
    { objs: [{ type: 'line', id: 'l7', p: ['B', 'C'] }],
      cap: 'Extension. Line BC — the vertical tangent at B; BC = r.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c10', center: 'E3', rad: ['P', 'X'] }],
      pts: [{ name: 'D3', on: ['c10', 'AXIS'], near: [-4.5, 0] }],
      cap: 'Circle about E with radius PX = 3r/2 (transfer); D beyond E, so BD = 11r/2.', cost: 1 },
    { objs: [{ type: 'line', id: 'l8', p: ['D3', 'C'] }], cap: 'Line DC.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c11', center: 'G', rad: ['D3', 'C'] }, { type: 'circle', id: 'c12', center: 'C', rad: ['D3', 'G'] }],
      pts: [{ name: 'M1', on: ['c11', 'c12'], near: [6.375, 1] }],
      cap: 'Parallelogram method for the parallel to DC through G (two transfer circles).', cost: 2 },
    { objs: [{ type: 'line', id: 'l9', p: ['G', 'M1'] }],
      pts: [{ name: 'U', on: ['l9', 'l7'], near: [1, 0.0227273] }],
      cap: 'The parallel meets BC at U: BU = BC·BG/BD = r/44.', cost: 1 },
    { objs: [{ type: 'line', id: 'l10', p: ['D3', 'U'] }], cap: 'Line DU.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c13', center: 'G', rad: ['D3', 'U'] }, { type: 'circle', id: 'c14', center: 'U', rad: ['D3', 'G'] }],
      pts: [{ name: 'M2', on: ['c13', 'c14'], near: [6.375, 0.0227273] }],
      cap: 'Second parallelogram parallel (to DU through G).', cost: 2 },
    { objs: [{ type: 'line', id: 'l11', p: ['G', 'M2'] }],
      pts: [{ name: 'V', on: ['l11', 'l7'], near: [1, 0.0005165] }],
      cap: 'BV = BU/44 = r/44² = r/1936.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c15', center: 'W', rad: ['B', 'V'] }],
      pts: [{ name: 'J', on: ['c15', 'l1'], near: [0, 1.7315343] }],
      cap: 'Mark J on OW with WJ = BV (a microscopic transfer circle about W).', cost: 1 },
    { objs: [{ type: 'circle', id: 'c16', center: 'J', rad: ['O', 'B'] }, { type: 'circle', id: 'c17', center: 'B', rad: ['O', 'J'] }],
      pts: [{ name: 'M3', on: ['c16', 'c17'], near: [1, 1.7315343] }],
      cap: 'Parallelogram parallel through J to the axis.', cost: 2 },
    { objs: [{ type: 'line', id: 'l12', p: ['J', 'M3'] }], cap: 'The horizontal through J.', cost: 1 },
    { objs: [{ type: 'circle', id: 'c18', center: 'W', thru: 'I' }],
      pts: [{ name: 'L', on: ['c18', 'l12'], near: [1.7724539, 1.7315343] }],
      cap: 'Circle about W through I (collapsing-legal). It meets the horizontal at L: JL² = WI² − WJ² = 355/113 − 1/44⁴.', cost: 1 },
  ],
  answer: { p: ['J', 'L'], kind: 'side' },
},
];

/* ---------- hero plot data ---------- */
const PLOT_DATA = [
  { c: 'pub', s: 9,  d: 4.23, l: 'Kochański 1685 (length)', cid: 'koch' },
  { c: 'pub', s: 13, d: 4.32, l: 'Beatrix 2022 (published record)' },
  { c: 'pub', s: 24, d: 6.57, span: [24, 38], l: 'Ramanujan 1913', cid: 'ram1913' },
  { c: 'pub', s: 58, d: 9.0,  l: 'Ramanujan 1914 (8 decimal places)', cid: 'ram1914' },
  { c: 'pub', s: 68, d: 9.0,  l: 'Chu 2019 (≥68 strokes)' },
  { c: 'f5', s: 4, d: 4.42, l: 'Fable 5 — 4-stroke', cid: 'f5-4', frontier: true },
  { c: 'f5', s: 5, d: 6.24, l: 'Fable 5 — 5-stroke', cid: 'f5-5', frontier: true },
  { c: 'f5', s: 6, d: 7.37, l: 'Fable 5 — 6-stroke (pure)', cid: 'f5-6', frontier: true },
  { c: 'f5', s: 7, d: 8.05, l: 'Fable 5 — 7-stroke (pure)', cid: 'f5-7', frontier: true },
  { c: 'f5', s: 8, d: 8.17, l: 'Fable 5 — 8-stroke', cid: 'f5-8', frontier: true },
  { c: 'f5', s: 9, d: 8.99, l: 'Fable 5 — 9-stroke', cid: 'f5-9', frontier: true },
  { c: 'f5', s: 15, d: 6.57, l: 'Fable 5 — 15-move 355/113', cid: 'f5-15' },
  { c: 'sol', s: 14, d: 6.57, l: 'Sol 5.6 — 14-stroke 355/113', cid: 'sol14' },
  { c: 'sol', s: 27, d: 10.42, l: 'Sol 5.6 — high accuracy (27–28)', cid: 'sol28', frontier: true },
];
